"""test_payload_schema.py — validate_record and required_columns contract tests.

Covers:
- required_columns() returns exactly the column set from each schema
- validate_record() returns [] for well-formed records
- validate_record() returns errors for broken records (missing cols, bad values)
- validate_record() rejects unknown scenario keys
- Column sets match the five schemas defined in mouse-kql-schema.md exactly
- All records generated by scenario generators pass schema validation
"""

from datetime import datetime, timezone

import pytest

from generator.config import LabConfig
from generator.time_window import generate_timestamps
from generator.validation import validate_record, required_columns


FIXED_NOW = datetime(2026, 7, 15, 20, 0, 0, tzinfo=timezone.utc)

# ---------------------------------------------------------------------------
# Expected column sets (must match mouse-kql-schema.md exactly)
# ---------------------------------------------------------------------------

_EXPECTED_COLUMNS = {
    "virtualmachines": {
        "TimeGenerated", "Resource", "ResourceId", "Environment", "Region", "OSType",
        "CpuPercent", "MemoryAvailableMB", "MemoryTotalMB", "DiskName", "DiskFreePercent",
        "NetworkInBytes", "NetworkOutBytes",
    },
    "appservice": {
        "TimeGenerated", "Resource", "ResourceId", "Environment", "Region", "AppName",
        "RequestCount", "ResponseTimeMs", "ResponseTimeP95Ms", "Http2xxCount", "Http4xxCount",
        "Http5xxCount", "RestartCount", "PlanCpuPercent", "PlanMemoryPercent",
    },
    "aks": {
        "TimeGenerated", "Resource", "ResourceId", "Environment", "Region", "Namespace",
        "NodeName", "PodName", "ContainerName", "NodeCpuPercent", "NodeMemoryPercent",
        "PodCpuPercent", "PodMemoryPercent", "PodRestartCount", "PodPhase", "PodReason",
        "NodeStatus", "PVName", "PVUsagePercent", "HpaName", "HpaCurrentReplicas",
        "HpaMaxReplicas",
    },
    "azuresql": {
        "TimeGenerated", "Resource", "ResourceId", "Environment", "Region", "DatabaseName",
        "DtuPercent", "CpuPercent", "WorkerPercent", "ActiveConnections", "FailedConnections",
        "DeadlockCount", "StoragePercent", "StorageUsedMB", "StorageLimitMB",
        "QueryDurationMs", "QueryDurationP95Ms",
    },
    "apm": {
        "TimeGenerated", "Resource", "ResourceId", "Environment", "Region", "ItemType",
        "OperationName", "DurationMs", "IsSuccess", "ExceptionType", "ExceptionMessage",
        "DependencyType", "DependencyTarget", "DependencySuccess", "DependencyDurationMs",
        "SeverityLevel", "TraceId", "SpanId",
    },
}

# ---------------------------------------------------------------------------
# Minimal valid records per scenario
# ---------------------------------------------------------------------------

_VALID_RECORDS = {
    "virtualmachines": {
        "TimeGenerated": "2026-07-15T20:00:00+00:00",
        "Resource": "vm-prod-01",
        "ResourceId": (
            "/subscriptions/sub/resourceGroups/rg"
            "/providers/Microsoft.Compute/virtualMachines/vm-prod-01"
        ),
        "Environment": "prod",
        "Region": "southcentralus",
        "OSType": "Linux",
        "CpuPercent": 25.0,
        "MemoryAvailableMB": 4096.0,
        "MemoryTotalMB": 16384.0,
        "DiskName": "/",
        "DiskFreePercent": 50.0,
        "NetworkInBytes": 100000,
        "NetworkOutBytes": 50000,
    },
    "appservice": {
        "TimeGenerated": "2026-07-15T20:00:00+00:00",
        "Resource": "app-prod-api",
        "ResourceId": (
            "/subscriptions/sub/resourceGroups/rg"
            "/providers/Microsoft.Web/sites/app-prod-api"
        ),
        "Environment": "prod",
        "Region": "southcentralus",
        "AppName": "api-service",
        "RequestCount": 200,
        "ResponseTimeMs": 100.0,
        "ResponseTimeP95Ms": 250.0,
        "Http2xxCount": 195,
        "Http4xxCount": 4,
        "Http5xxCount": 1,
        "RestartCount": 0,
        "PlanCpuPercent": 25.0,
        "PlanMemoryPercent": 30.0,
    },
    "aks": {
        "TimeGenerated": "2026-07-15T20:00:00+00:00",
        "Resource": "aks-prod-01",
        "ResourceId": (
            "/subscriptions/sub/resourceGroups/rg"
            "/providers/Microsoft.ContainerService/managedClusters/aks-prod-01"
        ),
        "Environment": "prod",
        "Region": "southcentralus",
        "Namespace": "default",
        "NodeName": "aks-nodepool1-01",
        "PodName": "api-deployment-abc12",
        "ContainerName": "api",
        "NodeCpuPercent": 30.0,
        "NodeMemoryPercent": 40.0,
        "PodCpuPercent": 10.0,
        "PodMemoryPercent": 20.0,
        "PodRestartCount": 0,
        "PodPhase": "Running",
        "PodReason": "",
        "NodeStatus": "Ready",
        "PVName": "",
        "PVUsagePercent": 0.0,
        "HpaName": "hpa-api",
        "HpaCurrentReplicas": 3,
        "HpaMaxReplicas": 10,
    },
    "azuresql": {
        "TimeGenerated": "2026-07-15T20:00:00+00:00",
        "Resource": "sql-prod-01",
        "ResourceId": (
            "/subscriptions/sub/resourceGroups/rg"
            "/providers/Microsoft.Sql/servers/sql-prod-01"
        ),
        "Environment": "prod",
        "Region": "southcentralus",
        "DatabaseName": "db-main",
        "DtuPercent": 40.0,
        "CpuPercent": 25.0,
        "WorkerPercent": 10.0,
        "ActiveConnections": 20,
        "FailedConnections": 0,
        "DeadlockCount": 0,
        "StoragePercent": 35.0,
        "StorageUsedMB": 35840,
        "StorageLimitMB": 102400,
        "QueryDurationMs": 50.0,
        "QueryDurationP95Ms": 200.0,
    },
    "apm": {
        "TimeGenerated": "2026-07-15T20:00:00+00:00",
        "Resource": "svc-checkout",
        "ResourceId": (
            "/subscriptions/sub/resourceGroups/rg"
            "/providers/Microsoft.Web/sites/svc-checkout"
        ),
        "Environment": "prod",
        "Region": "southcentralus",
        "ItemType": "request",
        "OperationName": "GET /api/orders",
        "DurationMs": 50.0,
        "IsSuccess": True,
        "ExceptionType": "",
        "ExceptionMessage": "",
        "DependencyType": "",
        "DependencyTarget": "",
        "DependencySuccess": True,
        "DependencyDurationMs": 0.0,
        "SeverityLevel": 1,
        "TraceId": "abc123def456abc1abcd",
        "SpanId": "abc123de",
    },
}


# ===========================================================================
# Column set tests
# ===========================================================================

class TestColumnSets:
    @pytest.mark.parametrize("scenario_key", list(_EXPECTED_COLUMNS.keys()))
    def test_required_columns_match_schema(self, scenario_key):
        """required_columns() must return exactly the column set from mouse-kql-schema.md."""
        actual = set(required_columns(scenario_key))
        expected = _EXPECTED_COLUMNS[scenario_key]
        assert actual == expected, (
            f"Schema mismatch for '{scenario_key}':\n"
            f"  Extra in code (not in schema doc): {actual - expected}\n"
            f"  Missing from code (in schema doc): {expected - actual}"
        )

    @pytest.mark.parametrize("scenario_key", list(_EXPECTED_COLUMNS.keys()))
    def test_required_columns_count(self, scenario_key):
        """Column count matches expected schema width."""
        actual_count = len(required_columns(scenario_key))
        expected_count = len(_EXPECTED_COLUMNS[scenario_key])
        assert actual_count == expected_count

    def test_unknown_scenario_returns_empty_list(self):
        """required_columns() for an unknown key returns [] (not an error)."""
        result = required_columns("no_such_scenario")
        assert result == []


# ===========================================================================
# Valid records — should return no errors
# ===========================================================================

class TestValidRecords:
    @pytest.mark.parametrize("scenario_key", list(_VALID_RECORDS.keys()))
    def test_valid_record_returns_no_errors(self, scenario_key):
        """Well-formed record should produce an empty error list."""
        record = _VALID_RECORDS[scenario_key]
        errors = validate_record(scenario_key, record)
        assert errors == [], (
            f"Unexpected validation errors for '{scenario_key}': {errors}"
        )

    def test_unknown_scenario_key_returns_error(self):
        """Unknown scenario key returns a non-empty error list."""
        errors = validate_record("no_such_scenario", {})
        assert len(errors) == 1
        assert "Unknown scenario key" in errors[0]

    @pytest.mark.parametrize("scenario_key", list(_VALID_RECORDS.keys()))
    def test_validate_is_idempotent(self, scenario_key):
        """Calling validate_record twice on the same record gives the same result."""
        record = _VALID_RECORDS[scenario_key]
        assert validate_record(scenario_key, record) == validate_record(scenario_key, record)


# ===========================================================================
# Broken records — must produce errors
# ===========================================================================

class TestBrokenRecords:
    # ---- Missing columns ----

    def test_missing_cpu_percent(self):
        rec = dict(_VALID_RECORDS["virtualmachines"])
        del rec["CpuPercent"]
        errors = validate_record("virtualmachines", rec)
        assert any("Missing column" in e and "CpuPercent" in e for e in errors), errors

    def test_missing_time_generated(self):
        rec = dict(_VALID_RECORDS["appservice"])
        del rec["TimeGenerated"]
        errors = validate_record("appservice", rec)
        assert any("Missing column" in e and "TimeGenerated" in e for e in errors), errors

    def test_missing_pod_phase(self):
        rec = dict(_VALID_RECORDS["aks"])
        del rec["PodPhase"]
        errors = validate_record("aks", rec)
        assert any("Missing column" in e and "PodPhase" in e for e in errors), errors

    def test_missing_database_name(self):
        rec = dict(_VALID_RECORDS["azuresql"])
        del rec["DatabaseName"]
        errors = validate_record("azuresql", rec)
        assert any("Missing column" in e and "DatabaseName" in e for e in errors), errors

    def test_missing_item_type(self):
        rec = dict(_VALID_RECORDS["apm"])
        del rec["ItemType"]
        errors = validate_record("apm", rec)
        assert any("Missing column" in e and "ItemType" in e for e in errors), errors

    # ---- Out-of-range percentage values ----

    def test_cpu_percent_above_100(self):
        rec = dict(_VALID_RECORDS["virtualmachines"])
        rec["CpuPercent"] = 150.0
        errors = validate_record("virtualmachines", rec)
        assert any("CpuPercent" in e for e in errors), errors

    def test_disk_free_percent_below_zero(self):
        rec = dict(_VALID_RECORDS["virtualmachines"])
        rec["DiskFreePercent"] = -5.0
        errors = validate_record("virtualmachines", rec)
        assert any("DiskFreePercent" in e for e in errors), errors

    def test_plan_cpu_above_100(self):
        rec = dict(_VALID_RECORDS["appservice"])
        rec["PlanCpuPercent"] = 101.0
        errors = validate_record("appservice", rec)
        assert any("PlanCpuPercent" in e for e in errors), errors

    def test_dtu_above_100(self):
        rec = dict(_VALID_RECORDS["azuresql"])
        rec["DtuPercent"] = 105.0
        errors = validate_record("azuresql", rec)
        assert any("DtuPercent" in e for e in errors), errors

    def test_storage_below_zero(self):
        rec = dict(_VALID_RECORDS["azuresql"])
        rec["StoragePercent"] = -1.0
        errors = validate_record("azuresql", rec)
        assert any("StoragePercent" in e for e in errors), errors

    # ---- Non-negative violations ----

    def test_negative_network_in_bytes(self):
        rec = dict(_VALID_RECORDS["virtualmachines"])
        rec["NetworkInBytes"] = -1
        errors = validate_record("virtualmachines", rec)
        assert any("NetworkInBytes" in e for e in errors), errors

    def test_negative_request_count(self):
        rec = dict(_VALID_RECORDS["appservice"])
        rec["RequestCount"] = -10
        errors = validate_record("appservice", rec)
        assert any("RequestCount" in e for e in errors), errors

    def test_negative_pod_restart_count(self):
        rec = dict(_VALID_RECORDS["aks"])
        rec["PodRestartCount"] = -1
        errors = validate_record("aks", rec)
        assert any("PodRestartCount" in e for e in errors), errors

    def test_negative_active_connections(self):
        rec = dict(_VALID_RECORDS["azuresql"])
        rec["ActiveConnections"] = -5
        errors = validate_record("azuresql", rec)
        assert any("ActiveConnections" in e for e in errors), errors

    def test_negative_duration_ms(self):
        rec = dict(_VALID_RECORDS["apm"])
        rec["DurationMs"] = -100.0
        errors = validate_record("apm", rec)
        assert any("DurationMs" in e for e in errors), errors

    # ---- Invalid SeverityLevel ----

    def test_severity_level_5_invalid(self):
        rec = dict(_VALID_RECORDS["apm"])
        rec["SeverityLevel"] = 5
        errors = validate_record("apm", rec)
        assert any("SeverityLevel" in e for e in errors), errors

    def test_severity_level_negative_invalid(self):
        rec = dict(_VALID_RECORDS["apm"])
        rec["SeverityLevel"] = -1
        errors = validate_record("apm", rec)
        assert any("SeverityLevel" in e for e in errors), errors

    # ---- Multiple errors reported ----

    def test_multiple_errors_in_single_record(self):
        rec = dict(_VALID_RECORDS["virtualmachines"])
        rec["CpuPercent"] = 200.0        # out of range
        rec["DiskFreePercent"] = -10.0   # out of range
        rec["NetworkInBytes"] = -1       # negative
        errors = validate_record("virtualmachines", rec)
        assert len(errors) >= 3, (
            f"Expected at least 3 errors, got {len(errors)}: {errors}"
        )

    # ---- Empty record ----

    def test_empty_record_missing_all_columns(self):
        errors = validate_record("virtualmachines", {})
        assert len(errors) == len(required_columns("virtualmachines"))
        assert all("Missing column" in e for e in errors)


# ===========================================================================
# Integration: all generated records pass schema validation
# ===========================================================================

@pytest.fixture(scope="module")
def dry_config():
    return LabConfig.load(dry_run=True)


@pytest.fixture(scope="module")
def fixed_time_window():
    return generate_timestamps(
        backfill_minutes=5, interval_seconds=60, now=FIXED_NOW
    )


class TestGeneratedRecordsValidation:
    """Every record emitted by the generators must pass schema validation."""

    def test_vm_records_pass_validation(self, dry_config, fixed_time_window):
        from generator.scenarios.virtual_machines import generate
        records = generate(dry_config, fixed_time_window, seed=42)
        for i, rec in enumerate(records):
            errors = validate_record("virtualmachines", rec)
            assert errors == [], (
                f"VM record #{i} failed validation: {errors}\nRecord: {rec}"
            )

    def test_appservice_records_pass_validation(self, dry_config, fixed_time_window):
        from generator.scenarios.app_service import generate
        records = generate(dry_config, fixed_time_window, seed=42)
        for i, rec in enumerate(records):
            errors = validate_record("appservice", rec)
            assert errors == [], (
                f"AppService record #{i} failed validation: {errors}"
            )

    def test_aks_records_pass_validation(self, dry_config, fixed_time_window):
        from generator.scenarios.aks import generate
        records = generate(dry_config, fixed_time_window, seed=42)
        for i, rec in enumerate(records):
            errors = validate_record("aks", rec)
            assert errors == [], (
                f"AKS record #{i} failed validation: {errors}\nRecord: {rec}"
            )

    def test_azuresql_records_pass_validation(self, dry_config, fixed_time_window):
        from generator.scenarios.azure_sql import generate
        records = generate(dry_config, fixed_time_window, seed=42)
        for i, rec in enumerate(records):
            errors = validate_record("azuresql", rec)
            assert errors == [], (
                f"AzureSQL record #{i} failed validation: {errors}"
            )

    def test_apm_records_pass_validation(self, dry_config, fixed_time_window):
        from generator.scenarios.apm import generate
        records = generate(dry_config, fixed_time_window, seed=42)
        for i, rec in enumerate(records):
            errors = validate_record("apm", rec)
            assert errors == [], (
                f"APM record #{i} failed validation: {errors}\nRecord: {rec}"
            )

    def test_vm_anomaly_cpu_records_pass_validation(self, dry_config, fixed_time_window):
        """Anomaly records (cpu) must also pass the validator — CpuPercent is 0-100."""
        from generator.scenarios.virtual_machines import generate
        records = generate(dry_config, fixed_time_window, anomaly="cpu", seed=42)
        for i, rec in enumerate(records):
            errors = validate_record("virtualmachines", rec)
            assert errors == [], (
                f"VM cpu-anomaly record #{i} failed validation: {errors}"
            )

    def test_aks_crashloop_records_pass_validation(self, dry_config, fixed_time_window):
        """crashloop anomaly records must still satisfy the column schema."""
        from generator.scenarios.aks import generate
        records = generate(dry_config, fixed_time_window, anomaly="crashloop", seed=42)
        for i, rec in enumerate(records):
            errors = validate_record("aks", rec)
            assert errors == [], (
                f"AKS crashloop record #{i} failed validation: {errors}"
            )

    def test_azuresql_deadlock_records_pass_validation(self, dry_config, fixed_time_window):
        from generator.scenarios.azure_sql import generate
        records = generate(dry_config, fixed_time_window, anomaly="deadlock", seed=42)
        for i, rec in enumerate(records):
            errors = validate_record("azuresql", rec)
            assert errors == [], (
                f"AzureSQL deadlock record #{i} failed validation: {errors}"
            )
