#!/usr/bin/env bash
# scripts/common.sh — shared helpers; source at the top of every script.
#   source "$(dirname "$0")/common.sh"
set -euo pipefail

# ---------------------------------------------------------------------------
# Repo root — callers live in scripts/, SCRIPT_DIR resolves to scripts/
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# ---------------------------------------------------------------------------
# Defaults (each overridable via environment variable before sourcing)
# ---------------------------------------------------------------------------
LAB_SUBSCRIPTION_ID="${LAB_SUBSCRIPTION_ID:-$(az account show --query id -o tsv 2>/dev/null)}"
LAB_NAME_PREFIX="${LAB_NAME_PREFIX:-amlab}"
LAB_LOCATION="${LAB_LOCATION:-southcentralus}"

# ---------------------------------------------------------------------------
# assert_az_cli — verify az CLI is installed and the user is logged in
# ---------------------------------------------------------------------------
assert_az_cli() {
    if ! command -v az &>/dev/null; then
        echo "ERROR: az CLI not found. Install from https://aka.ms/installazurecli" >&2
        exit 1
    fi
    if ! az account show &>/dev/null; then
        echo "ERROR: Not logged in to Azure. Run: az login" >&2
        exit 1
    fi
    echo "  az CLI: OK"
}

# ---------------------------------------------------------------------------
# set_az_subscription — az account set --subscription <id>
# ---------------------------------------------------------------------------
set_az_subscription() {
    local sub="${1:-$LAB_SUBSCRIPTION_ID}"
    echo "  Setting subscription: $sub"
    az account set --subscription "$sub"
}

# ---------------------------------------------------------------------------
# write_lab_env — write config/lab.env from exported shell variables.
# All variables must be set before calling this function.
# ---------------------------------------------------------------------------
write_lab_env() {
    local env_path="${REPO_ROOT}/config/lab.env"
    mkdir -p "$(dirname "$env_path")"
    local ts
    ts="$(date -u +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || date +%Y-%m-%dT%H:%M:%S)"

    cat >"$env_path" <<EOF
# =============================================================================
# config/lab.env — generated by scripts/deploy on ${ts}
# DO NOT EDIT — re-run scripts/deploy to regenerate.
# =============================================================================

# --- Lab-wide settings -------------------------------------------------------
LAB_LOCATION=${LAB_LOCATION}
LAB_RESOURCE_GROUP=${LAB_RESOURCE_GROUP}
LAB_SUBSCRIPTION_ID=${LAB_SUBSCRIPTION_ID}

# --- Log Analytics Workspace -------------------------------------------------
LAW_NAME=${LAW_NAME}
# Workspace customer GUID (for KQL workspace() calls)
LAW_ID=${LAW_ID}
# Full ARM resource ID of the workspace
LAW_RESOURCE_ID=${LAW_RESOURCE_ID}

# --- Data Collection Endpoint ------------------------------------------------
# Logs Ingestion endpoint URL (https://<dce-id>.<region>.ingest.monitor.azure.com)
DCE_LOGS_INGESTION_ENDPOINT=${DCE_LOGS_INGESTION_ENDPOINT}

# =============================================================================
# Per-scenario bindings (one block per scenario)
# DCR_IMMUTABLE_ID_<SCENARIO>  — immutableId from the deployed DCR resource
# STREAM_<SCENARIO>            — stream name used in the ingestion call
# TABLE_<SCENARIO>             — destination custom table in the workspace
# =============================================================================

# --- Virtual Machines --------------------------------------------------------
DCR_IMMUTABLE_ID_VIRTUAL_MACHINES=${DCR_IMMUTABLE_ID_VIRTUAL_MACHINES}
STREAM_VIRTUAL_MACHINES=${STREAM_VIRTUAL_MACHINES}
TABLE_VIRTUAL_MACHINES=${TABLE_VIRTUAL_MACHINES}

# --- App Service -------------------------------------------------------------
DCR_IMMUTABLE_ID_APP_SERVICE=${DCR_IMMUTABLE_ID_APP_SERVICE}
STREAM_APP_SERVICE=${STREAM_APP_SERVICE}
TABLE_APP_SERVICE=${TABLE_APP_SERVICE}

# --- AKS ---------------------------------------------------------------------
DCR_IMMUTABLE_ID_AKS=${DCR_IMMUTABLE_ID_AKS}
STREAM_AKS=${STREAM_AKS}
TABLE_AKS=${TABLE_AKS}

# --- Azure SQL ---------------------------------------------------------------
DCR_IMMUTABLE_ID_AZURE_SQL=${DCR_IMMUTABLE_ID_AZURE_SQL}
STREAM_AZURE_SQL=${STREAM_AZURE_SQL}
TABLE_AZURE_SQL=${TABLE_AZURE_SQL}

# --- APM (Applications) ------------------------------------------------------
DCR_IMMUTABLE_ID_APM=${DCR_IMMUTABLE_ID_APM}
STREAM_APM=${STREAM_APM}
TABLE_APM=${TABLE_APM}
EOF
    echo "  lab.env written → $env_path"
}
