#Requires -Version 5.1
# scripts/common.ps1 — shared helpers; dot-source at the top of every script.
# Each powershell call is a fresh process, so all state is re-established on
# every dot-source.
[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'

# ---------------------------------------------------------------------------
# Repo root — callers live in scripts/, so PSScriptRoot is scripts/
# ---------------------------------------------------------------------------
$script:RepoRoot = Split-Path -Parent $PSScriptRoot

# ---------------------------------------------------------------------------
# Defaults (each overridable via environment variable before dot-sourcing)
# ---------------------------------------------------------------------------
if (-not $env:LAB_SUBSCRIPTION_ID) { $env:LAB_SUBSCRIPTION_ID = (az account show --query id -o tsv 2>$null) }
if (-not $env:LAB_NAME_PREFIX)     { $env:LAB_NAME_PREFIX     = 'amlab' }
if (-not $env:LAB_LOCATION)        { $env:LAB_LOCATION        = 'southcentralus' }

$script:SubscriptionId = $env:LAB_SUBSCRIPTION_ID
$script:NamePrefix     = $env:LAB_NAME_PREFIX
$script:Location       = $env:LAB_LOCATION

# ---------------------------------------------------------------------------
# Assert-AzCli — verify az CLI is installed and the user is logged in
# ---------------------------------------------------------------------------
function Assert-AzCli {
    [CmdletBinding()]
    param()
    if (-not (Get-Command az -ErrorAction SilentlyContinue)) {
        throw 'az CLI not found. Install from https://aka.ms/installazurecli'
    }
    $null = az account show 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw 'Not logged in to Azure. Run: az login'
    }
    Write-Host '  az CLI: OK'
}

# ---------------------------------------------------------------------------
# Set-AzSubscription — az account set --subscription <id>
# ---------------------------------------------------------------------------
function Set-AzSubscription {
    [CmdletBinding()]
    param(
        [string]$SubscriptionId = $script:SubscriptionId
    )
    Write-Host "  Setting subscription: $SubscriptionId"
    az account set --subscription $SubscriptionId
    if ($LASTEXITCODE -ne 0) { throw "az account set failed for subscription '$SubscriptionId'" }
}

# ---------------------------------------------------------------------------
# Write-LabEnv — write config/lab.env from a hashtable of key=value pairs
# ---------------------------------------------------------------------------
function Write-LabEnv {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [hashtable]$Vars,

        [string]$Path = (Join-Path $script:RepoRoot 'config\lab.env')
    )

    $dir = Split-Path -Parent $Path
    if (-not (Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir | Out-Null
    }

    $ts = Get-Date -Format 'yyyy-MM-ddTHH:mm:ss'

    $content = @"
# =============================================================================
# config/lab.env — generated by scripts/deploy on $ts
# DO NOT EDIT — re-run scripts/deploy to regenerate.
# =============================================================================

# --- Lab-wide settings -------------------------------------------------------
LAB_LOCATION=$($Vars['LAB_LOCATION'])
LAB_RESOURCE_GROUP=$($Vars['LAB_RESOURCE_GROUP'])
LAB_SUBSCRIPTION_ID=$($Vars['LAB_SUBSCRIPTION_ID'])

# --- Log Analytics Workspace -------------------------------------------------
LAW_NAME=$($Vars['LAW_NAME'])
# Workspace customer GUID (for KQL workspace() calls)
LAW_ID=$($Vars['LAW_ID'])
# Full ARM resource ID of the workspace
LAW_RESOURCE_ID=$($Vars['LAW_RESOURCE_ID'])

# --- Data Collection Endpoint ------------------------------------------------
# Logs Ingestion endpoint URL (https://<dce-id>.<region>.ingest.monitor.azure.com)
DCE_LOGS_INGESTION_ENDPOINT=$($Vars['DCE_LOGS_INGESTION_ENDPOINT'])

# =============================================================================
# Per-scenario bindings (one block per scenario)
# DCR_IMMUTABLE_ID_<SCENARIO>  — immutableId from the deployed DCR resource
# STREAM_<SCENARIO>            — stream name used in the ingestion call
# TABLE_<SCENARIO>             — destination custom table in the workspace
# =============================================================================

# --- Virtual Machines --------------------------------------------------------
DCR_IMMUTABLE_ID_VIRTUAL_MACHINES=$($Vars['DCR_IMMUTABLE_ID_VIRTUAL_MACHINES'])
STREAM_VIRTUAL_MACHINES=$($Vars['STREAM_VIRTUAL_MACHINES'])
TABLE_VIRTUAL_MACHINES=$($Vars['TABLE_VIRTUAL_MACHINES'])

# --- App Service -------------------------------------------------------------
DCR_IMMUTABLE_ID_APP_SERVICE=$($Vars['DCR_IMMUTABLE_ID_APP_SERVICE'])
STREAM_APP_SERVICE=$($Vars['STREAM_APP_SERVICE'])
TABLE_APP_SERVICE=$($Vars['TABLE_APP_SERVICE'])

# --- AKS ---------------------------------------------------------------------
DCR_IMMUTABLE_ID_AKS=$($Vars['DCR_IMMUTABLE_ID_AKS'])
STREAM_AKS=$($Vars['STREAM_AKS'])
TABLE_AKS=$($Vars['TABLE_AKS'])

# --- Azure SQL ---------------------------------------------------------------
DCR_IMMUTABLE_ID_AZURE_SQL=$($Vars['DCR_IMMUTABLE_ID_AZURE_SQL'])
STREAM_AZURE_SQL=$($Vars['STREAM_AZURE_SQL'])
TABLE_AZURE_SQL=$($Vars['TABLE_AZURE_SQL'])

# --- APM (Applications) ------------------------------------------------------
DCR_IMMUTABLE_ID_APM=$($Vars['DCR_IMMUTABLE_ID_APM'])
STREAM_APM=$($Vars['STREAM_APM'])
TABLE_APM=$($Vars['TABLE_APM'])
"@

    Set-Content -Path $Path -Value $content -Encoding UTF8
    Write-Host "  lab.env written → $Path"
}
